apiVersion: apps/v1
kind: Deployment
metadata:
  name: frent-admin-deployment
  labels:
    app: frent-admin
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frent-admin
  template:
    metadata:
      labels:
        app: frent-admin
    spec:
      containers:
      - name: frent-admin
        image: soulredouane/react-bmce-admin:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
          - name: REACT_APP_BACK_END_API_URL
            valueFrom:
               configMapKeyRef:
                name: frent-config
                key:   backend-host
---
apiVersion: v1
kind: Service
metadata:
  name: admin-frent-service
spec:
  type: NodePort
  selector:
   app: frent-admin
  ports:
  - name: f-service-port
    protocol: TCP
    port: 80
    targetPort: 3000
    nodePort:  30008