apiVersion: v1
kind: ConfigMap
metadata:
  name: frent-config
data:
  backend-host: backend-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frent-deployment
  labels:
    app: frent
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frent
  template:
    metadata:
      labels:
        app: frent
    spec:
      containers:
      - name: frent
        image: soulredouane/react-bmce:1.0
        ports:
        - containerPort: 3000
        env:
          - name: REACT_APP_BACK_END_API_URL
            valueFrom:
               configMapKeyRef:
                name: frent-config
                key:   backend-host
---
apiVersion: v1
kind: Service
metadata:
  name: main-frent-service
spec:
  type: NodePort
  selector:
   app: frent
  ports:
  - name: f-service-port
    protocol: TCP
    port: 80
    targetPort: 3000